#:kivy 2.0.0
<MyRoot>: 

    result_label: result_label

    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "MyLabel"
            font_size: 64
            color: 0.9, 0.1, 0.4
        
        Label:
            id: result_label
            text: "-"
            font_size: 64
        Button:
            text: "Generate"
            font_size: 32
            size: 100, 50
            on_press: root.generate_number()
